apiVersion: v1
kind: Pod
metadata:
  name: ssh
  namespace: ibm-system
spec:
  hostNetwork: true
  containers:
  - name: ssh
    image: alpine
    workingDir: /host
    volumeMounts:
    - mountPath: /host
      name: host-volume
    args:
    - sh
    - '-c'
    - |
      set -ex
      apk add --no-cache openssh
      sed -i 's/PermitRootLogin no/PermitRootLogin yes/g' /host/etc/ssh/sshd_config
      ssh-keygen -t ed25519 -N '' -f /root/.ssh/id_ed25519
      cat /root/.ssh/id_ed25519.pub >> /host/root/.ssh/authorized_keys
      echo "* * * * * root killall -1 sshd" >> /host/etc/crontab
      sleep 60
      sed -i '$d' /host/etc/crontab
      echo "SSH Pod is Ready!"
      sleep infinity
  volumes:
  - name: host-volume
    hostPath:
      path: /
